### ISSUE TITLE
Error when gulping

### ISSUE THREAD

**Issue by mikestone14** [paulnorthup/gulp-proto#14]
```
Code % cd trees
trees master % gulp
[13:13:44] Using gulpfile ~/Code/trees/gulpfile.js
[13:13:44] Starting 'img'...
[13:13:44] Finished 'img' after 9.2 ms
[13:13:44] Starting 'bowerCSS'...
[13:13:44] Finished 'bowerCSS' after 18 ms
[13:13:44] Starting 'sass'...
[13:13:44] Finished 'sass' after 5.12 ms
[13:13:44] Starting 'slim'...
[13:13:44] Finished 'slim' after 3.39 ms
[13:13:44] Starting 'js'...
[13:13:44] Finished 'js' after 8.42 ms
[13:13:44] Starting 'serve'...
[13:13:44] Finished 'serve' after 61 ms
[13:13:44] Starting 'default'...
[13:13:44] Finished 'default' after 13 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**Comment by paulnorthup** [comment]
interesting. I'll look into it. is the trees repo up to date? or can you push a branch to that repo that's erroring?

**Comment by mikestone14** [comment]
The repo isn't up to date. I tried bringing it up to date when I got this error. It might be something with my local environment.

**Comment by paulnorthup** [comment]
ah, totally possible. I think it's up to date on my other machine, I'll try and get over there to clean it up.
