### ISSUE TITLE
After installing Gulp locally, I get an error when trying to run it

### ISSUE THREAD

**Issue by briandant** [paulnorthup/gulp-proto#3]
Error: 

```
(startupinstitute.com)➜  gulp-proto git:(master) gulp
[17:18:40] Using gulpfile ~/dev/playground/gulp-proto/gulpfile.js
[17:18:40] Starting 'sass'...
[17:18:40] Finished 'sass' after 11 ms
[17:18:40] Starting 'slim'...
[17:18:40] Finished 'slim' after 3.69 ms
[17:18:40] Starting 'serve'...
[17:18:40] Finished 'serve' after 30 ms
[17:18:40] Starting 'default'...
[17:18:40] Finished 'default' after 14 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

Could maybe be related to the install of node-gyp, which I got this output from (this looks like success? but weird that it's throwing that builderror.log?): 

```
(startupinstitute.com)➜  gulp-proto git:(master) npm install
npm WARN package.json birthday@0.0.0 No repository field.
/
> ws@0.4.31 install /Users/chaz/dev/playground/gulp-proto/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /Users/chaz/dev/playground/gulp-proto/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
```

**Comment by andreicojea** [comment]
Hey @paulnorthup, how did you fix this after all? I just followed the steps in README, error still there. Re installed slim gem, same thing... Do you have any idea?

**Comment by andreicojea** [comment]
That was a problem with my `.bashrc`, one line was preventing `rvm` to load default ruby, and `slimrb` couldn't be run from command line. That's why `gulp-slim` was throwing that error, because it couldn't execute `slimrb`.

**Comment by paulnorthup** [comment]
@andreicojea interesting. So are you all set now? I can put a note in the readme to address this if you think it'd be helpful down the line.

**Comment by andreicojea** [comment]
@paulnorthup I don't know, I think my problem was somehow unrelated to the project. Maybe you can note something like "make sure you can run `slimrb` after doing `gem install slim`, otherwise `rvm` may not be referenced correctly in your `PATH`". 

The error above `Error: write EPIPE` happens when `slimrb` fails to execute for whatever reason :-)
